#!/bin/sh
mydir=$(cd $(dirname $0) && echo $PWD)

export PATH=${mydir}:$PATH
export MANPATH=/home/fultonm/zopen/prod/vim/share/man

if ! groff --version 2>/dev/null ; then
  cd $HOME/zopen/prod/groff
  . ./.env
  cd $mydir
fi
if ! man --version 2>/dev/null ; then
  cd $HOME/zopen/prod/man
  . ./.env
  cd $mydir
fi

man -d vim 


#(cd /home/fultonm/zopen/prod/vim/share/man && /home/fultonm/zopen/prod/man-db-2.10.2/libexec/man-db/zsoelim) | (cd /home/fultonm/zopen/prod/vim/share/man && /home/fultonm/zopen/prod/man-db-2.10.2/libexec/man-db/manconv -f UTF-8:ISO-8859-1 -t UTF-8) | (cd /home/fultonm/zopen/prod/vim/share/man && preconv -e UTF-8) | (cd /home/fultonm/zopen/prod/vim/share/man && tbl) | (cd /home/fultonm/zopen/prod/vim/share/man && nroff -mandoc -rLL=183n -rLT=183n -Tutf8)
#iconv -c -f UTF-8 -t ISO-8859-1 | col -b -p -x | sed -e '/^[[:space:]]*$/{ N; /^[[:space:]]*\n[[:space:]]*$/D; }'

#cd /home/fultonm/zopen/prod/vim/share/man 

#cat /home/fultonm/zopen/prod/vim/share/man/man1/vim.1 | /home/fultonm/zopen/prod/man-db-2.10.2/libexec/man-db/zsoelim >/tmp/zsoelim.$$.out

#/home/fultonm/zopen/prod/man-db-2.10.2/libexec/man-db/manconv -f UTF-8:ISO-8859-1 -t UTF-8 </tmp/zsoelim.$$.out >/tmp/manconv.$$.out

#preconv -e UTF-8 </tmp/manconv.$$.out >/tmp/preconv.$$.out

#tbl </tmp/preconv.$$.out >/tmp/tbl.$$.out

#nroff -mandoc -Tutf8 </tmp/tbl.$$.out >/tmp/nroff.$$.out

#iconv -c -f UTF-8 -t ISO-8859-1 </tmp/nroff.$$.out >/tmp/iconv.$$.out
#chtag -tcISO8859-1 /tmp/iconv.$$.out

#col -b -p -x </tmp/iconv.$$.out >/tmp/col.$$.out

#sed -e '/^[[:space:]]*$/{ N; /^[[:space:]]*\n[[:space:]]*$/D; }' </tmp/col.$$.out # >/tmp/sed.$$.out
